### ISSUE TITLE
Document services available in `hsdp_config`

### ISSUE THREAD

**Issue by ScottGuymer** [philips-software/terraform-provider-hsdp#106]
Add some documentation to indicate which services can i query details for in `hsdp_config`

I know we can do `iam` but not sure what else

**Comment by loafoe** [comment]
Note the list varies across regions and environments so a configured data source as shown above would give you the valid list in the given context. Please close issue if this is satisfactory

**Comment by ScottGuymer** [comment]
I'm wondering what the best way of "discovering" which things you can use where are..

I think documenting the "possible" options somewhere would be useful with the disclaimer that they are not available in all regions and that you should check the datasource to see exactly what is available.

**Comment by loafoe** [comment]
Makes sense, I'll see if I can expand the `hsdp_config` with a table that lists the available services
