### ISSUE TITLE
Script continues to run even when resource creation fails. Error can only be seen when Debug logs are enabled

### ISSUE THREAD

**Issue by kishoreinvits** [philips-software/terraform-provider-hsdp#110]
For below resources, observed that they continue to show creating resource forever(until timeout) in terraform. When debug log is enabled, it is clear that there is a HTTP request that failed with a reason. Instead of reporting a failure and stopping there, terraform continues endlessly.

Observed this with `hsdp_dicom_remote_node` , `hsdp_dicom_gateway_config`

```
module.dicom_cdr_data_org[0].hsdp_dicom_object_store.object_store: Still creating... [59m0s elapsed]
module.dicom_cdr_data_org[0].hsdp_dicom_gateway_config.dicom_gateway: Still creating... [59m0s elapsed]
module.dicom_cdr_data_org[1].hsdp_dicom_gateway_config.dicom_gateway: Still creating... [59m0s elapsed]
module.dicom_cdr_data_org[1].hsdp_dicom_repository.dicom_repository: Still creating... [59m0s elapsed]
module.dicom_cdr_data_org[0].hsdp_dicom_object_store.object_store: Still creating... [59m10s elapsed]
module.dicom_cdr_data_org[0].hsdp_dicom_gateway_config.dicom_gateway: Still creating... [59m10s elapsed]
module.dicom_cdr_data_org[1].hsdp_dicom_gateway_config.dicom_gateway: Still creating... [59m10s elapsed]
module.dicom_cdr_data_org[1].hsdp_dicom_repository.dicom_repository: Still creating... [59m10s elapsed]

```

Observed this on version [0.18.9](https://registry.terraform.io/providers/philips-software/hsdp/0.18.9)

In the past observed similar behavior for `hsdp_dicom_object_store`, `hsdp_dicom_repository` but I cannot confirm if it is still the case

This can be reproduced by using service identity with insufficient privileges.

**Comment by loafoe** [comment]
@kishoreinvits are you able to share the debug log with the failed HTTP error?

**Comment by loafoe** [comment]
There is retry code that deal with an IAM race condition in case permissions are set as part of the Terraform run itself. This provider implements an exponential backoff retry mechanism. I've reduced the maximum number of tries a bit. This might solve it, but even the existing max values should not retry for an hour, so there might be some other issue. The upcoming release will have this improvement, so if you can try it out that would be great.

**Comment by loafoe** [comment]
[0.19.3](https://registry.terraform.io/providers/philips-software/hsdp/0.19.3) fixes a very subtle bug that could cause the provider to get stuck. This only happens if you are using a service identity for IAM auth. Are you using a service identity?

**Comment by kishoreinvits** [comment]
@loafoe Yes, we are using a service identity. Our hsdp provider configuration looks like below.

```
provider "hsdp" {
  region              = var.HSDP_REGION
  environment         = var.HSDP_ENVIRONMENT
  service_id          = data.azurerm_key_vault_secret.devopsserviceid.value # For IAM org admin operations
  service_private_key = data.azurerm_key_vault_secret.devopsserviceprivatekey.value
  debug_log           = "${path.module}/terraform.log" # Enable this for debug logs from hsdp module
}
```

**Comment by kishoreinvits** [comment]
> @kishoreinvits are you able to share the debug log with the failed HTTP error?

Debug log in this bug #109 also causes this.

**Comment by loafoe** [comment]
@kishoreinvits if you can rerun your scripts with `0.19.3+` and confirm the issue is resolved that would be great

**Comment by kishoreinvits** [comment]
@loafoe - It does not run infinitely now. I got an immediate failure with failure reason. Tested with `0.19.3`

Thank You for the fix! Closing this.
