### ISSUE TITLE
Add members to existing IAM groups

### ISSUE THREAD

**Issue by jdelucaa** [philips-software/terraform-provider-hsdp#152]
Hi 👋 

Can we extend the provider so that it has the capability of adding members to an existing IAM group? We have use cases where one config will create the group and another config will assign members to that group.

IAM offers an endpoint for that too:
https://www.hsdp.io/documentation/identity-and-access-management-iam/api-documents/resource-reference-api/user-api/group-api#/Group%20Management/post_Group__id___add_members

Thanks 😄

**Comment by loafoe** [comment]
@jdelucaa yeah we have been thinking for a while about a `hsdp_iam_group_membership` resource which would allow this without having the group declaration in Terraform itself i.e. use a data source to look up the IAM group and then describe the user / service membership. We will pick it up this week.

**Comment by loafoe** [comment]
@jdelucaa available in `v0.27.11`
