### ISSUE TITLE
Running with parallel deployment causes 'required permission' issues 

### ISSUE THREAD

**Issue by Darren-Vine** [philips-software/terraform-provider-hsdp#159]
Hi,

This is a follow on from ticket 'INC0067775'.  The hsdp module does not seem to fetch the correct token and relies on an old token with invalid permissions if we have modified it in the deployment.  This causes our build to fail unless we set parallelism to 1.  This bloats our deployment times from 10 minutes to well over an hour and this blocks the teams during this time.  

Ideally, we need the module to be more aggressive with retries and fetching tokens if it cannot determine the dependencies at the start of the apply stage.

**Comment by loafoe** [comment]
@Darren-Vine thanks, will look into creating a more coherent retry/refresh mechanism throughout the provider. Currently, we add retries to individual code paths and a change in one worker could cause the need to refresh in potentially other workers, especially if there are "hidden" dependencies across scripts.

**Comment by loafoe** [comment]
@Darren-Vine closing this one for now as you have refactored the code
