### ISSUE TITLE
Resource hsdp_connect_mdm_oauth_client returns empty strings for secrets

### ISSUE THREAD

**Issue by JWintermans** [philips-software/terraform-provider-hsdp#169]
A mdm POST call for OAuthClient (hsdp_connect_mdm_oauth_client) returns empty strings for client_bootstrap_secret and client_secret.  Where at least one of them should contain a value based on the user_client variable.

**Comment by loafoe** [comment]
@JWintermans should be fixed in `v0.30.3` , are you able to test?

**Comment by JWintermans** [comment]
Tested and working as expected in `v0.30.3`
