### ISSUE TITLE
HSDP provider crashes

### ISSUE THREAD

**Issue by TamirNator** [philips-software/terraform-provider-hsdp#173]
while trying to create subscriptions in CDR i get the following error:

Error: Plugin did not respond
panic: runtime error: invalid memory address or nil pointer dereference
The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
contain more details.

i was able to do it the first time in different space, from then on i get error

![Capture](https://user-images.githubusercontent.com/45774725/157005132-d7f98c2b-39e4-4948-8378-dbf129e6f3d2.PNG)

**Comment by loafoe** [comment]
@TamirNator you left out the most important part, the Go stack trace :)

**Comment by TamirNator** [comment]
![Capture2](https://user-images.githubusercontent.com/45774725/157213576-e7a5247d-b14d-4e76-804b-4ba0e1eecb3e.PNG)


added more detailed screenshot

**Comment by loafoe** [comment]
Thanks, changed the error handling and you should get an error message now instead of a crash. Please try `v0.30.7`

**Comment by loafoe** [comment]
@TamirNator the init code allowed usage of an uninitialized IAM Client under some conditions. This was ultimately the root cause of this problem. There are additional checks in place to fix this. Thanks for reporting the issue and providing the stack traces!
