### ISSUE TITLE
[Feature] Enhance IAM terraform module to reflect API changes in march 2022 release

### ISSUE THREAD

**Issue by balajinarayanaa** [philips-software/terraform-provider-hsdp#184]
API changes listed below:

|Resource|Version|Status|
|----------|--------|-------|
GET /authorize/scim/v2/Configurations/ScopePermissionMap|1|New - List ScopePermissionMap for a scope
GET /authorize/scim/v2/Configurations/ScopePermissionMap/{id}|1|New - Retrieve an existing ScopePermissionMap based on ID
POST /authorize/identity/Client|1|UPDATED - Blocked *, % and / characters from being used for ClientId
POST /authorize/identity/Service|1|UPDATED - Blocked *, % and / characters from being used for Service name.
GET /authorize/oauth2/v2/.well-known/openid-configuration||UPDATED - OpenID discovery endpoint to return grant_types_supported attribute
POST /authorize/identity/Group/{id}/$add-members|1|UPDATED - Introduced new permission HSDP_IAM_GROUP.ADD_USER to allow fine-grained access to add membership capability
POST /authorize/identity/Group/{id}/$remove-members|1|UPDATED - Introduced new permission HSDP_IAM_GROUP.REMOVE_USER to allow fine-grained access to add membership capability
POST /authorize/identity/Group/{id}/$assign|1|UPDATED - Introduced new permission HSDP_IAM_GROUP.ADD_MEMBER to allow fine-grained access to add membership capability
POST /authorize/identity/Group/{id}/$remove|1|UPDATED - Introduced new permission HSDP_IAM_GROUP.REMOVE_MEMBER to allow fine-grained access to add membership capability
POST /authorize/identity/Group/{id}/$assign-role|1|UPDATED - Introduced new permission HSDP_IAM_GROUP.ADD_ROLE to allow fine-grained access to add membership capability
POST /authorize/identity/Group/{id}/$remove-role|1|UPDATED - Introduced new permission HSDP_IAM_GROUP.REMOVE_ROLE to allow fine-grained access to add membership capability
POST /authorize/identity/Role/{id}/$remove-permission|1|UPDATED - Introduced new permission HSDP_IAM_ROLE.REMOVE_PERMISSION to allow fine-grained access to add membership capability
POST /authorize/identity/Role/{id}/$assign-permission|1|UPDATED - Introduced new permission HSDP_IAM_ROLE.ADD_PERMISSION to allow fine-grained access to add membership capability
PUT /authorize/identity/Role/{id}/$apply-sharing-policy|1|NEW - Create or update a role sharing policy.
GET /authorize/identity/Role/{id}/$list-sharing-policies|1|NEW - Search for existing sharing policies.
DELETE /authorize/identity/Role/{id}/$remove-sharing-policy|1|NEW - delete/revoke an existing sharing policy.
GET /authorize/identity/User/{id}|2|UPDATED - Support for query federated IDP providers names for a given user.
GET /authorize/identity/User/{id}|3|UPDATED - Support for query federated IDP providers names for a given user.
GET /authorize/scim/v2/Organizations/{id}|2|UPDATED - Support for query configured IDP names for a given organization.
PUT /authorize/identity/Service/{id}|1|NEW - Added support to update the description and token validity.
POST /authorize/access/Policy|1|UDATED - Increase in the policy creation limit.
GET /authorize/access/Policy|1|UDATED - Can return up to 200 policies.

**Comment by loafoe** [comment]
@balajinarayanaa thanks. Most of these changes do not require any change in the provider. The ones I can identify:

1. Sharing policy concept
2. IAM Service: token validity configuration

Will look at 2, while trying to find a good example use case for applying 1.
