### ISSUE TITLE
Existing terraform state is broken due to TASK.DELETE permission as invalid permissions

### ISSUE THREAD

**Issue by dilliplkumar** [philips-software/terraform-provider-hsdp#190]
Error: error adding permission 'TASK.DELETE': POST : StatusCode 404, Body: {"resourceType":"OperationOutcome","issue":[{"severity":"error","code":"invalid","details":{"coding":{"code":"31103"},"text":"Invalid Permission(s)"}}]}
  with module.iam_tenant["15c58b7f-d62f-4d8d-8cd3-909fea0ec1ff"].hsdp_iam_role.developeruser,
  on ../../modules/iam_tenant/main.tf line 77, in resource "hsdp_iam_role" "developeruser":
  77: resource "hsdp_iam_role" "developeruser" {
We are facing this issue after last upgrade, our terraform state is broken - could you please suggest?

After removing the permission from the role, we are getting following error

Error: POST : StatusCode 404, Body: {"resourceType":"OperationOutcome","issue":[{"severity":"error","code":"invalid","details":{"coding":{"code":"31103"},"text":"Invalid Permission(s)"}}]}
  with module.iam_tenant["e309bc7d-873c-4f67-bceb-02bac48b25fc"].hsdp_iam_role.developeruser,
  on ../../modules/iam_tenant/main.tf line 77, in resource "hsdp_iam_role" "developeruser":
  77: resource "hsdp_iam_role" "developeruser" {
Error: POST : StatusCode 404, Body: {"resourceType":"OperationOutcome","issue":[{"severity":"error","code":"invalid","details":{"coding":{"code":"31103"},"text":"Invalid Permission(s)"}}]}
  with module.iam_tenant["9077b7b3-e1f4-48f4-94ca-c82899dda0a4"].hsdp_iam_role.developeruser,
  on ../../modules/iam_tenant/main.tf line 77, in resource "hsdp_iam_role" "developeruser":
  77: resource "hsdp_iam_role" "developeruser" {

**Comment by loafoe** [comment]
@dilliplkumar instead of erroring on invalid permissions the provider will now emit warnings and continue the apply, allowing the state to be cleared of invalid permissions. Invalid permissions should no longer make it to the state as the stricter check is also performed during role creation.
