### ISSUE TITLE
CDR Configuration

### ISSUE THREAD

**Issue by ScottGuymer** [philips-software/terraform-provider-hsdp#22]
Any plans to include CDR configuration into this provider?

Being able to model the configuration of orgs in the CDR or other settings would be useful.

**Comment by loafoe** [comment]
@ScottGuymer this is planned, most likely starting with data sources first. Also, currently there is tendency to deploy a CDR per tenant, so configuration of CDR would need to be injected at the data/resource level. 

Can you provide a concrete example of how you would model this? Hypothetical HCL would be fine 👍

**Comment by ScottGuymer** [comment]
Some thoughts

- Provisioning of the instance itself is not possible via terraform, so a data source is needed for it.
- Resource for onboarding an IAM org into the CDR


Im still at the start of using it so not sure what else is needed yet.

**Comment by ScottGuymer** [comment]
I thought that the CDR was multi-tenant and you would have one CDR instance per application/region and then create tenants within the CDR for each organisation using it?

Hypothetical, maybe something like this.....

```
data "hsdp_cdr" "mycdr" {
 id = "abc-123"
}

data "hsdp_iam_org" "myorg" {
  id = "xyz 123"
}

resource "hsdp_cdr_org" "myfirstorg" {
  cdr_id = data.hsdp_cdr.mycdr.id
  iam_org_id = data.hsdp_iam_org.myorg.id
}
```

**Comment by krmeda** [comment]
My experience has been that a ROOT CDR Instance is created which corresponds to a corresponding IAM ORG using Tickets. From then on, we are allowed to create FHIR Organizations using the `/store/fhir/<Root_IAM_Org_ID>/Organization/<IAM_Org_ID>` if I am not mistaken. so probably HCL can be tweaked to indicate parent org details...

 ```
data "hsdp_cdr" "mycdr" {
 id = "abc-123" // Not sure we need this...
 endpoint = "https://.../store/fhir/<ROOT_IAM_ORG_ID>"
}

data "hsdp_iam_org" "rootOrg" {
  id = "xyz 123"
}

resource "hsdp_iam_org" "institution1" {
// IAM Org creation.
}

resource "hsdp_cdr_org" "myfirstorg" {
  root_cdr_endpoint = data.hsdp_cdr.mycdr.endpoint
  iam_org_id = data.hsdp_iam_org.institution1.id
 // Not sure how you are giving the Access Token.
}
```

**Comment by ScottGuymer** [comment]
The docs state this

> Starting with the July 2019 release, tenants would have to onboard themselves manually by self-service. Onboarding of tenants via deployment will no longer be available from this release onwards.

Im not sure if its referring to the root org or additional orgs however.. Im still quite early on in my exploration and usage of CDR.

**Comment by loafoe** [comment]
@ScottGuymer @krmeda onboarding of the root CDR Org is indeed a self-service activty. This should probably be the first implementation. Unfortunately some of the REST calls are not well balanced so the provider needs to be a bit creative forgetting and rediscovering resources in case the REST APIs do not allow deletion.

**Comment by loafoe** [comment]
Started adding some basic interaction in philips-software/go-hsdp-api#28

**Comment by loafoe** [comment]
Implemented the minimal data source and resource to facilitate IAM Org onboarding. Adding the `name` field required baking in support for FHIR operations in philips-software/go-hsdp-api but support PATCH-ing the Organization.

```hcl
data "hsdp_cdr_instance" "sandbox" {
  base_url = "https://cdr-stu3-sandbox.us-east.philips-healthsuite.com"
}

resource "hsdp_cdr_org" "myorg" {
  fhir_store = data.hsdp_cdr_instance.sandbox.fhir_store
  root_org_id = var.iam_org_id
  org_id = var.iam_org_id

  name = "Hospital"
}
```

Another useful resource to add would be `hsdp_cdr_subscription` which would allow one to configure web hooks in CDR and having it point to Terraform managed services. That will probably not be in the initial release of CDR support. For now only `EHR` CDR is supported. The `PHR` variant will follow once I've dived a bit more into CDR.

**Comment by loafoe** [comment]
@ScottGuymer if you can test drive the CDR resources that would be great! I've openen a separate discussion topic https://github.com/philips-software/terraform-provider-hsdp/discussions/27  on possible broader support of CDR resources, we should continue the discussion there. Closing this one.

**Comment by ScottGuymer** [comment]
Thanks for this @loafoe 

Will try and give it a go when I get out from under this mountain of email 😄
