### ISSUE TITLE
Need Terraform resource for HSP Logging service - Log Admin API 

### ISSUE THREAD

**Issue by yasar-m** [philips-software/terraform-provider-hsdp#224]
HSP logging service has provided a Log Admin API to configure custom data types to allow visualization in Kibana.

https://www.hsdp.io/documentation/logging/api-documents/log-admin-api

We have HDS application log service instances in multiple Region/environment.

So need a terraform support to apply the same configuration in all the region/environments similar to dicom store configuration resources.

**Comment by yasar-m** [comment]
@loafoe

**Comment by loafoe** [comment]
@yasar-m I looked at this in the past but this API does not fit the CRUD model that is typically required to create a meaningful Terraform resource. If you can provide an example of how such a resource would look in your context that would already help in starting up the discussion. Please share here, thanks!

**Comment by yasar-m** [comment]
> @yasar-m I looked at this in the past but this API does not fit the CRUD model that is typically required to create a meaningful Terraform resource. If you can provide an example of how such a resource would look in your context that would already help in starting up the discussion. Please share here, thanks!

@loafoe  
we have multiple HDS solution deployments which are deployed and configured via terraform and terragrunt.
below is a sample use case which will expand to more environments and regions 
Root -> Client-Test  -> US-EAST
                                -> EU-WEST
                                
          -> Production -> US-EAST
                                  -> EU-WEST                                  
           -> Staging  -> US-EAST                                  

When we add any new env/regions. the same logging admin API configuration should be applied for new enviroment instances also without any manual work.  Same as how the Dicom store configuration and CDR org creations are automated via terraform.
@balajinarayanaa

**Comment by loafoe** [comment]
please reopen once you have proposal for moving this forward
