### ISSUE TITLE
Requesting an additional attribute "storeAsComposite" to be added to the hsdp_dicom_repository attribute in the Dicom Store Terraform Provider.

### ISSUE THREAD

**Issue by rahul-balaji** [philips-software/terraform-provider-hsdp#230]
In the Dicom Store Repository Configuration [ dicomRepositories ] , We are passing an attribute "storeAsComposite": True  via the API’s.

Similarly We need an additional attribute "storeAsComposite" to be added to the hsdp_dicom_repository attribute in the Dicom Store Terraform Provider.

**Comment by loafoe** [comment]
This is implemented in #232 , thanks to @roopesh83 for initiating the PR!
