### ISSUE TITLE
Expose MDM GUID for resource hsdp_connect_mdm_proposition

### ISSUE THREAD

**Issue by BerndDA** [philips-software/terraform-provider-hsdp#272]
More a feature request:
Documentation is a little bit misleading because it states that the GUID is exposed by the resource.
In fact it is not the MDM GUID but the resource GUID.

Adding the MDM GUID would be really helpful for us.

Regards
Bernd

**Comment by loafoe** [comment]
hi @BerndDA , both `id` and `guid` are available as attributes. Are you referring to `PropositionGuid` ? I don't this is currently exposed but can be added easily, let me know.. thanks!

**Comment by BerndDA** [comment]
@loafoe yes. I mean the PropositionGuid. We would need this to configure services that query other MDM resources based on this Guid. We could spare some additional API calls by having this in the configuration rather than querying the proposition by name...

**Comment by loafoe** [comment]
@BerndDA cool, I'll add ` proposition_guid` attribute. It is probably the case well for MDM application as well. Stay tuned for this

**Comment by BerndDA** [comment]
@loafoe great! thanks a lot!

**Comment by loafoe** [comment]
@BerndDA available in `0.38.11`

**Comment by BerndDA** [comment]
@loafoe may I ask to add the same to the corresponding data sources? This would be awesome!

**Comment by loafoe** [comment]
Ah, yes.. will add that as well, will reopen to track it

**Comment by loafoe** [comment]
@BerndDA data source updated in `0.38.12`

**Comment by BerndDA** [comment]
thanks. works perfectly!
