### ISSUE TITLE
Issue in creating IAM sub-org

### ISSUE THREAD

**Issue by P12Shilpa** [philips-software/terraform-provider-hsdp#288]
Hi Team,

Recently I have encountered one issue while creating IAM org (sub-org under root org) using terraform. Below is the error:
│ Error: retry 0 permanent: POST : StatusCode 400, Body: {"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"status":"400","scimType":"invalidSyntax","detail":"**Value for multi-valued attribute owners must be a JSON array"**}
│
│   with module.proposition["Onboard-tenant1-M"].hsdp_iam_org.proposition,
│   on modules\proposition\iam_platform.tf line 5, in resource "hsdp_iam_org" "proposition":
│    5: resource "hsdp_iam_org" "proposition" {
**Terraform Logs:**
[go-hsdp-api b1ee8144-ff6f-4928-9f26-7927f560fe2d-00008 2022-12-01T07:10:18.2275115Z] --- request start ---
POST /authorize/scim/v2/Organizations HTTP/1.1
Host: [idm-development.us-east.philips-healthsuite.com](http://idm-development.us-east.philips-healthsuite.com/)
Accept: application/json
Api-Version: 2
Authorization: [sensitive]
Content-Type: application/json
User-Agent: go-hsdp-api/iam/0.75.6
{"schemas":["urn:ietf:params:scim:schemas:core:philips:hsdp:2.0:Organization"],"id":"","name":"ONBOARD-TENANT1-M","description":"Module proposition for HSD DaaS","parent":{"value":"10fdf5aa-d064-415b-b8d4-e55f4ee1194e"},"address":{},"owners":null,"createdBy":{},"modifiedBy":{}}
[go-hsdp-api b1ee8144-ff6f-4928-9f26-7927f560fe2d-00008 2022-12-01T07:10:18.2275115Z] --- request end ---
[go-hsdp-api b1ee8144-ff6f-4928-9f26-7927f560fe2d-00008 2022-12-01T07:10:19.4337444Z] --- response start ---
HTTP/1.1 400 Bad Request
Content-Length: 173
Connection: keep-alive
Content-Type: application/json
Date: Thu, 01 Dec 2022 07:10:19 GMT
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
X-Newrelic-App-Data: PxQOUlFQDAETUlBVBAACU1UDFB9AMQYAZBBZDEtZV0ZaClc9HjJWEBJaUhU6TFtcXUoRCl5dXhYXH15ABhZNEVUBTRBRTE0cWgFUFwNPYAENW2FTJxNIX1kHABZeXllESAEYA1NUT1IeUwhVCAoFAQZJFFAdQwpaUgdUVgdRWwYAUVdbAAAVSgJQWkAHOw==
X-Vcap-Request-Id: 09c1ea3a-16fb-4dd6-6f17-feba8fc5c592
{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"status":"400","scimType":"invalidSyntax","detail":"Value for multi-valued attribute owners must be a JSON array"}
[go-hsdp-api b1ee8144-ff6f-4928-9f26-7927f560fe2d-00008 2022-12-01T07:10:19.4337444Z] --- response end ---

**Problem what I investigated using POSTMAN API is in the request body:**
{"schemas":["urn:ietf:params:scim:schemas:core:philips:hsdp:2.0:Org
anization"],"id":"","name":"ONBOARD-TENANT1-M","description":"Module proposition for HSD DaaS","parent":{"value":"10fdf5aa-d064-415b-b8d4-e55f4ee1194e"},"address":{},"owners":null,"createdBy":{},"modifiedBy":{}}

**My finding from the below request body:**
{"schemas":["urn:ietf:params:scim:schemas:core:philips:hsdp:2.0:Organization"],"id":"","name":"ONBOARD-TENANT1-M","description":"Module proposition for HSD DaaS","parent":{"value":"10fdf5aa-d064-415b-b8d4-e55f4ee1194e"},"address":{},"owners":null,"createdBy":{},"modifiedBy":{}}
===> Error message : Value for multi-valued attribute owners must be a JSON array
**And in IAM API specification, the "owners" attribute is JSON array and that could be the issue.**

**I have even downgraded to hsdp-provdider to version 0.38.13 and issue still persists.**

Please look into this issue at the earliest. Thanks in advance.

**Comment by loafoe** [comment]
Looks like the `owner` field is `null` and is no longer accepted by IAM development. Will provide a fix for this shortly
