### ISSUE TITLE
IAM - Delete Applications API

### ISSUE THREAD

**Issue by jdelucaa** [philips-software/terraform-provider-hsdp#291]
IAM now has an endpoint to delete HSDP IAM Applications:
https://www.hsdp.io/documentation/identity-and-access-management-iam/api-documents/scim-application-api-v1#/Application/delete_Applications__id_

Can we update the provider so we can make use of it when managing the iam_application resource? 😄 
Thanks :)

**Comment by loafoe** [comment]
@jdelucaa this is planned yes
