### ISSUE TITLE
cdr_org documentation refers to wrong argument name

### ISSUE THREAD

**Issue by jdelucaa** [philips-software/terraform-provider-hsdp#30]
Hi,

I am trying out the new available resource `hsdp_cdr_org` by following the documentation, but it seems that the documentation is referring to an unsupported argument: `root_org_id`, while the correct argument name is `fhir_org_id`. The doc needs an update :)

I am sending a PR to fix it.

**Comment by jdelucaa** [comment]
Actually, I can't push: 
`ERROR: Permission to philips-software/terraform-provider-hsdp.git denied to jdelucaa.`

**Comment by loafoe** [comment]
@jdelucaa please fork the repo and push your changes to your fork and then create a PR, thanks!
