### ISSUE TITLE
CDR: provider trying to force replace orgs in update runs in case purge_delete is enabled

### ISSUE THREAD

**Issue by akodhawan** [philips-software/terraform-provider-hsdp#300]
Case: created some IAM Role/Perms & CDR root org as first run, then trying to add a CDR subOrg under the root
And see that the root org needed a force replacement - which kinda didn’t make sense IMO 

`purge_delete` seems to reflect even in apply runs & requires `ORGANIZATION.WRITE/PURGE` even when not executing destroy, forcing org replacement (& assume data cleanup with it as Org gets destroyed)

Extended scenario: Post execution of above executed something simple as update IAM `Permission` and provider planned replacement of both the CDR Orgs as forced replaced with same IDs.

![image](https://user-images.githubusercontent.com/87007141/214022899-88d142ab-4f82-42d8-b0d4-099842f4be08.png)

Expected behaviour:
- `purge_delete`  should reflect ONLY for `destroy`
- CDR orgs _should not be destroyed_ & replaced (in case update needed for reference then `PUT` should be used), as this can result into data loss where it was not intended IMO :)

**Comment by loafoe** [comment]
@akodhawan the `plan` suggests a change in the `fhir_store` URL in the data source, which in turn caused a change in the `endpooint` argument of the resources which forces a replacement, which is expected behaviour. Can you confirm no changes were made to the `hsdp_cdr_fhir_store` data source?

**Comment by akodhawan** [comment]
@loafoe yup & that is the part which is strange as `fhir_store` has not changed (same base url & same iam org id)

**Comment by loafoe** [comment]
@akodhawan after our discussion it is clear where this `diff` is coming from. The `ForceNew` fields is not desired as it will almost never be the correct change. I'm adding a customDiff function which will error out as a start. There is one possible caveat in that the Terraform documentation states that `known after apply` values are not supported there which is exactly what is happening in your case. We may need to introduce actual `resources` for instances but I was reserving these for the days when we are actually able to provision such service via Terraform. This use case might force us to adopt full resources ahead of schedule.

**Comment by akodhawan** [comment]
@loafoe  agree on adding `fhir_store` resource but that needs more detailing / investigation.
Proposal for now:
`Short Term`: advice based on doc to implement `fhir_store` based on pattern - `base url` / `cdr org` or chain it from resource (rather from data source)
`Long Term`:  add `fhir_store` resource

**Comment by loafoe** [comment]
Closing as CDR is deprecated 😢
