### ISSUE TITLE
Ability to run tasks on request

### ISSUE THREAD

**Issue by tonb** [philips-software/terraform-provider-hsdp#378]
We use siderite together with the `hsdp-func-gateway` to run tasks periodically using a `cron` schedule.

For automated end-to-end testing, it would be great if we can trigger a task on request via a POST to the gateway api, that bypasses the `cron` schedule.

This would require a way to identify the tasks automatically, e.g., by name?

**Comment by loafoe** [comment]
Won't implement due to deprecation of the Iron services, sorry.
