### ISSUE TITLE
HSDP IAM now allows defining password for hsdp_iam_user

### ISSUE THREAD

**Issue by EriksonBahr** [philips-software/terraform-provider-hsdp#38]
As of today [it is possible to define a password to an `hsdp_iam_user`](https://www.hsdp.io/announcement/iam-january-2021-release) and coincidently I was having problems with it today when creating a default user for my team in a test environment.

I'm willing to pick this small change up, but it might take few days to get this done😄. If anyone else has higher priority to get this implemented feel free to do so!

**Comment by loafoe** [comment]
Nice new capability! The first step would be to add support for the new API version and fields in the philips-software/go-hsdp-api library around here:

https://github.com/philips-software/go-hsdp-api/blob/4bfb465b070a43bb270f820d41775b4763c7017d/iam/users_service.go#L70-L78

**Comment by loafoe** [comment]
@EriksonBahr there is an incoming PR with this feature #53

**Comment by EriksonBahr** [comment]
Thanks! Looking forward to try it out 👍
