### ISSUE TITLE
Request to provide a feature to migrate users in bulk from one org to another

### ISSUE THREAD

**Issue by ragnaray** [philips-software/terraform-provider-hsdp#380]
Usecase: We have a requirement where there are about 100 users registered for one mobile app in HSDP IAM. They all belong to an IAM org say Org1 and a group say group1. All these users have been created using api calls. Some of them using selfservice UI. We now need to migrate them in go from Org1 to Org2 and/or add them to group2 under Org2. This could be required while migrating from say dev to qa or qa to prod or from one mobile app to another.
This needs to be done using terraform so that it can be automatic, parameterised.

**Comment by loafoe** [comment]
After looking at the effort have decided not to implement this at the provider level, recommend you look into using [go-hsdp-api](https://github.com/philips-software/go-hsdp-api) directly to script your migration.
