### ISSUE TITLE
Request to modify the provider to ignore non terraform additions when drift detection is disabled.

### ISSUE THREAD

**Issue by ragnaray** [philips-software/terraform-provider-hsdp#410]
Create a group in IAM using terraform. Create users using HSDP apis outside of terraform and add the users to this group.
Modify the terraform script to create any unrelated resource and run terraform apply.
Observe that the script tries to update all users in place too. This inspite of setting drift_detection = false.

![image](https://github.com/philips-software/terraform-provider-hsdp/assets/13623849/510f5d05-4aa5-4ca7-bb7c-8679419286b8)

**Comment by loafoe** [comment]
@ragnaray `drift_detection` should be enabled during initial apply of the Group resource. If you retroactively enable it then the state might still contain entries which will be reconciled on the next plan/apply cycle. Once an apply has run with `drift_detection = false`, subsequent plans will ignore any entries outside of your Terraform declarations.
