### ISSUE TITLE
Intermittent iron.io errors upon deploy.

### ISSUE THREAD

**Issue by tonb** [philips-software/terraform-provider-hsdp#424]
When we deploy docker containers to iron.io, we intermittently get the response: 'No name, required parameter' from the iron.io API POST /projects/{Project ID}/codes, documented here: https://dev.iron.io/worker/reference/api/

This API is called from Andy's terraform provider on this line:

https://github.com/philips-software/go-hsdp-api/blob/3eefb88c7057d21c3c565efbfcb1d1e83e26e340/iron/codes_services.go#L65

In our build log we see:

``Error: CreateOrUpdateCode(&{ <nil>   docker.eu1.hsdp.io/dev-isd-data-distribution/isdindexcreator:tonBrouwer-624  0  <nil>}): empty code value: 'No name, required parameter'``

The behaviour is erratic, i.e., one time the deploy succeeds, the next time it fails without any changes from our side.

We would like guidance on how to debug this.

**Comment by loafoe** [comment]
Should be solved in 0.49.0, assuming the issue is related to intermittent API issues on Iron.io side
