### ISSUE TITLE
Updating global_reference_id on hsdp_iam_proposition & hsdp_iam_application doesn't work

### ISSUE THREAD

**Issue by gjkamstra** [philips-software/terraform-provider-hsdp#44]
Use something like this:
resource "hsdp_iam_proposition" "prop" {
  name                = upper("${var.environment}-propositon")
  description         = "${var.environment} Proposition"
  organization_id     = hsdp_iam_org.suborg.id
  **global_reference_id = "2c5e8525-d9e5-81a6-8e9b-fb887d0f2d90"**
}

Now update the global_reference_id. 
When you apply, Terraform indicates that an update is needed and applies this after confirming.
From now on, all terraform apply calls will update the proposition, despite there being no changes. It indicates the previous global_reference_id is still current, and hence requires an update again.

This also holds for the hsdp_iam_application resource that also has a global_reference_id. It does work for hsdp_iam_client though.

If you do a terraform destroy first and apply then, it is all okay.

**Comment by loafoe** [comment]
@gjkamstra unfortunately the current [IAM Proposition API](https://www.hsdp.io/documentation/identity-and-access-management-iam/api-documents/resource-reference-api/proposition-api#/) only supports creating a Proposition so the provider "fakes" the other operations as best as possible e.g. a `destroy` simply removes the state. When you create the same resource again it will first search for any existing Proposition that matches and will use that for the underlying resource. Effectively, it does means you cannot change the `global_reference_id` after initial creation. What can be done is mark the field as `ForceNew` and add an additional check for incoming values. The provider will then throw an error in this step which is better than pretending it did anything

**Comment by loafoe** [comment]
@gjkamstra error reporting and lifecycle management should be improved in `v0.12.1` for `Proposition` and `Application` resources. We'll monitor the IAM capabilities closely and once full CRUD operations are available the provider will add support for it.
