### ISSUE TITLE
Region and Environment values in provider config

### ISSUE THREAD

**Issue by ScottGuymer** [philips-software/terraform-provider-hsdp#59]
When using `hsdp_config` it would be good if it could pull through from values set in the provider for the region and environment. This would save having to push them through as variables to modules etc.

If they are not set on the provider it should probably error out if they are empty in the `hsdp_config`

**Comment by loafoe** [comment]
@ScottGuymer this has been the case since inception. Are you seeing different behaviour?

**Comment by ScottGuymer** [comment]
Yes, I found I had to explicitly state the config.

I haven't played with it since I logged this so would have to go back and re-confirm my original thoughts.

**Comment by loafoe** [comment]
See below, I think this is minimum config to demonstrate. The data source is picking up the region/environment from the provider. You can override this in the data source itself of course.

```hcl
terraform {
  required_providers {
    hsdp = {
      source  = "philips-software/hsdp"
      version = ">= 0.14.5"
    }
  }
}

provider "hsdp" {
   region = "eu-west"
   environment = "prod"
}


data "hsdp_config" "cf" {
  service = "cf"
}

output "domain" {
  value = data.hsdp_config.cf.domain
}
```

**Comment by ScottGuymer** [comment]
Must be something we are doing wrong somewhere!

**Comment by ScottGuymer** [comment]
@jdelucaa have you used this yet? to be able to get the IAM urls from config rather than hard coding them?

**Comment by jdelucaa** [comment]
Hi @ScottGuymer, yes! we do not hard code the IAM url anymore.

**Comment by ScottGuymer** [comment]
ok works well then!

I think i was just using it wrong!
