### ISSUE TITLE
Password policy not supported

### ISSUE THREAD

**Issue by jdelucaa** [philips-software/terraform-provider-hsdp#65]
Provider version: 0.14.2

When adding a resource of type "hsdp_iam_pasword_policy", I am getting the following error:

```
Error: Invalid resource type

  on main.tf line 31, in resource "hsdp_iam_pasword_policy" "password_policy":
  31: resource "hsdp_iam_pasword_policy" "password_policy" {

The provider provider.hsdp does not support resource type
"hsdp_iam_pasword_policy".
```

**Comment by loafoe** [comment]
@jdelucaa oops, there is a `typo` in the example. Will be fixed in the next release. If you add the extra `s` to hsdp_iam_pasSword_policy` it should work! Let me now..

**Comment by jdelucaa** [comment]
oh, can't believe I missed that! Copy/paste mistake! 
It works now, thanks!
