### ISSUE TITLE
Support Get task status from scheduler / ironworker

### ISSUE THREAD

**Issue by soubhagya-pradhan** [philips-software/terraform-provider-hsdp#84]
Currently hsdp_function is creating scheduled jobs which makes tasks run at scheduled time. Should add functionality to: 
- Support for getting scheduled task status.
-  Support for getting history of tasks ran for a scheduled job

**Comment by loafoe** [comment]
Please move this to: https://github.com/philips-labs/hsdp-function-gateway , thanks!
