### ISSUE TITLE
CDR Offboard fails when it has more than one sub orgs 

### ISSUE THREAD

**Issue by khhipparagi** [philips-software/terraform-provider-hsdp#96]
(Terraform destroy) CDR Offboard failing when managing org has 2 or more sub organizations. It is able to offboard one/two orgs and third org is failed. 

This is happening due to race condition. When it try to delete the managing root org id before deleting the sub organization
[terraform.log](https://github.com/philips-software/terraform-provider-hsdp/files/6890586/terraform.log)
.
[terraform.log](https://github.com/philips-software/terraform-provider-hsdp/files/6890572/terraform.log)
[terraform.log](https://github.com/philips-software/terraform-provider-hsdp/files/6890576/terraform.log)

╷                                                                                                                 
│ Warning: Experimental feature "module_variable_optional_attrs" is active                                        
│                                                                                                                 
│   on terraform.tf line 11, in terraform:                                                                        
│   11:   experiments = [module_variable_optional_attrs]                                                          
│                                                                                                                 
│ Experimental features are subject to breaking changes in future minor or patch releases, based on feedback.     
│                                                                                                                 
│ If you have feedback on the design of this feature, please open a GitHub issue to discuss it.                   
│                                                                                                                 
│ (and one more similar warning elsewhere)                                                                        
╵                                                                                                                 
╷                                                                                                                 
│ Error: DELETE : StatusCode 409: non http 20x CDR response                                                       
│

**Comment by loafoe** [comment]
@khhipparagi the `part_of` reference to the root org id should prevent this from happening. Is the `part_of` parameter of the sub org referring directly to the root org resource itself? If not, then Terraform does not know there is an hierarchical, so a `depends_on` might be required.  

Can you provide a link to the `.tf` or module where you are seeing this issue?
